# Generated by Django 5.0.1 on 2024-02-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('1', ' 0️⃣1️⃣'), ('2', ' 0️⃣2️⃣'), ('3', ' 0️⃣3️⃣'), ('4', ' 0️⃣4️⃣'), ('5', ' 0️⃣5️⃣'), ('6', ' 0️⃣6️⃣'), ('7', ' 0️⃣7️⃣'), ('8', ' 0️⃣8️⃣'), ('9', ' 0️⃣9️⃣'), ('10', '1️⃣0️⃣')], max_length=2),
        ),
    ]
