# Generated by Django 5.0.1 on 2024-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('1', ' 1️⃣'), ('2', ' 2️⃣'), ('3', ' 3️⃣'), ('4', ' 4️⃣'), ('5', ' 5️⃣'), ('6', ' 6️⃣'), ('7', ' 7️⃣'), ('8', ' 8️⃣'), ('9', ' 9️⃣'), ('10', '1️⃣0️⃣')], max_length=2),
        ),
    ]
